### ISSUE TITLE
Improve config.yaml

### ISSUE THREAD

**Issue by MrPrimate** [MrPrimate/aws_role_keys#1]
It would be more elegant to be able to load config like:

``` YAML
session_profile:
- name: session_profile_name
      id: AKIAKIAKIAKIAKI
      key: secretkeything
      mfa_arn: 'arn:aws:iam::1234678901:mfa/jack'
      expiry: 86400
      region: eu-west-1
      roles:
        - name: nameForProfileOrRole
          role_arn:  'arn:aws:iam::1234678901:role/rolename'
        - name: nameForProfileOrRole2
          role_arn:  'arn:aws:iam::0234678901:role/rolename2'


```
